[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Yape隐私计算框架"
authors = [{name = "Yape", email = "heyifei@pku.edu.cn"}]
dynamic = ["version", "description"]